site_name: My Docs Site
site_description: Documentation with Netlify CMS

theme:
  name: material

docs_dir: docs

include:
  - admin/**

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
